// LaTeX 命令和符号的完整数据库
// 基于 LaTeX Workshop 项目的数据结构
// 参考: https://github.com/James-Yu/LaTeX-Workshop

export const latexCompletionData = {
  // 基本命令和结构
  commands: [
    // 文档结构
    { name: 'documentclass', snippet: 'documentclass[${1:options}]{${2:class}}', description: 'Document class declaration', detail: 'Document setup' },
    { name: 'usepackage', snippet: 'usepackage[${1:options}]{${2:package}}', description: 'Use package', detail: 'Package import' },
    { name: 'begin', snippet: 'begin{${1:environment}}${2}\n\\end{${1:environment}}', description: 'Begin environment', detail: 'Environment' },
    { name: 'end', snippet: 'end{${1:environment}}', description: 'End environment', detail: 'Environment' },
    
    // 章节结构
    { name: 'part', snippet: 'part{${1:title}}', description: 'Part title', detail: 'Structure' },
    { name: 'chapter', snippet: 'chapter{${1:title}}', description: 'Chapter title', detail: 'Structure' },
    { name: 'section', snippet: 'section{${1:title}}', description: 'Section title', detail: 'Structure' },
    { name: 'subsection', snippet: 'subsection{${1:title}}', description: 'Subsection title', detail: 'Structure' },
    { name: 'subsubsection', snippet: 'subsubsection{${1:title}}', description: 'Subsubsection title', detail: 'Structure' },
    { name: 'paragraph', snippet: 'paragraph{${1:title}}', description: 'Paragraph title', detail: 'Structure' },
    { name: 'subparagraph', snippet: 'subparagraph{${1:title}}', description: 'Subparagraph title', detail: 'Structure' },
    
    // 文本格式
    { name: 'textbf', snippet: 'textbf{${1:text}}', description: 'Bold text', detail: 'Formatting' },
    { name: 'textit', snippet: 'textit{${1:text}}', description: 'Italic text', detail: 'Formatting' },
    { name: 'texttt', snippet: 'texttt{${1:text}}', description: 'Typewriter text', detail: 'Formatting' },
    { name: 'textsc', snippet: 'textsc{${1:text}}', description: 'Small caps text', detail: 'Formatting' },
    { name: 'underline', snippet: 'underline{${1:text}}', description: 'Underlined text', detail: 'Formatting' },
    { name: 'emph', snippet: 'emph{${1:text}}', description: 'Emphasized text', detail: 'Formatting' },
    
    // 引用和标签
    { name: 'label', snippet: 'label{${1:key}}', description: 'Label for referencing', detail: 'Reference' },
    { name: 'ref', snippet: 'ref{${1:key}}', description: 'Reference to label', detail: 'Reference' },
    { name: 'eqref', snippet: 'eqref{${1:key}}', description: 'Equation reference', detail: 'Reference' },
    { name: 'cite', snippet: 'cite{${1:key}}', description: 'Citation', detail: 'Citation' },
    { name: 'pageref', snippet: 'pageref{${1:key}}', description: 'Page reference', detail: 'Reference' },
    
    // 列表
    { name: 'item', snippet: 'item ${1}', description: 'List item', detail: 'List' },
    { name: 'item[]', snippet: 'item[${1:label}] ${2}', description: 'List item with custom label', detail: 'List' },
    
    // 数学模式
    { name: '\\(', snippet: '\\(${1}\\)', description: 'Inline math', detail: 'Math' },
    { name: '\\[', snippet: '\\[${1}\\]', description: 'Display math', detail: 'Math' },
    
    // 空格和换行
    { name: '\\\\', snippet: '\\\\\\\\', description: 'Line break', detail: 'Spacing' },
    { name: 'newline', snippet: 'newline', description: 'New line', detail: 'Spacing' },
    { name: 'newpage', snippet: 'newpage', description: 'New page', detail: 'Spacing' },
    { name: 'clearpage', snippet: 'clearpage', description: 'Clear page', detail: 'Spacing' },
    { name: 'quad', snippet: 'quad', description: 'Quad space', detail: 'Spacing' },
    { name: 'qquad', snippet: 'qquad', description: 'Double quad space', detail: 'Spacing' },
    { name: ',', snippet: ',', description: 'Thin space', detail: 'Spacing' },
    { name: ':', snippet: ':', description: 'Medium space', detail: 'Spacing' },
    { name: ';', snippet: ';', description: 'Thick space', detail: 'Spacing' },
    { name: '!', snippet: '!', description: 'Negative space', detail: 'Spacing' },
    
    // 脚注
    { name: 'footnote', snippet: 'footnote{${1:text}}', description: 'Footnote', detail: 'Note' },
    { name: 'marginpar', snippet: 'marginpar{${1:text}}', description: 'Margin note', detail: 'Note' },
    
    // 包含文件
    { name: 'input', snippet: 'input{${1:filename}}', description: 'Input file', detail: 'File' },
    { name: 'include', snippet: 'include{${1:filename}}', description: 'Include file', detail: 'File' },
    { name: 'includeonly', snippet: 'includeonly{${1:filelist}}', description: 'Include only specified files', detail: 'File' },
    
    // 表格
    { name: 'hline', snippet: 'hline', description: 'Horizontal line in table', detail: 'Table' },
    { name: 'cline', snippet: 'cline{${1:i-j}}', description: 'Partial horizontal line', detail: 'Table' },
    { name: 'multicolumn', snippet: 'multicolumn{${1:cols}}{${2:pos}}{${3:text}}', description: 'Multi-column cell', detail: 'Table' },
    { name: 'multirow', snippet: 'multirow{${1:rows}}{${2:width}}{${3:text}}', description: 'Multi-row cell', detail: 'Table' },
  ],

  // 希腊字母 (小写)
  greekLettersLower: [
    { name: 'alpha', symbol: 'α', description: 'Greek letter alpha' },
    { name: 'beta', symbol: 'β', description: 'Greek letter beta' },
    { name: 'gamma', symbol: 'γ', description: 'Greek letter gamma' },
    { name: 'delta', symbol: 'δ', description: 'Greek letter delta' },
    { name: 'epsilon', symbol: 'ϵ', description: 'Greek letter epsilon' },
    { name: 'varepsilon', symbol: 'ε', description: 'Greek letter varepsilon' },
    { name: 'zeta', symbol: 'ζ', description: 'Greek letter zeta' },
    { name: 'eta', symbol: 'η', description: 'Greek letter eta' },
    { name: 'theta', symbol: 'θ', description: 'Greek letter theta' },
    { name: 'vartheta', symbol: 'ϑ', description: 'Greek letter vartheta' },
    { name: 'iota', symbol: 'ι', description: 'Greek letter iota' },
    { name: 'kappa', symbol: 'κ', description: 'Greek letter kappa' },
    { name: 'lambda', symbol: 'λ', description: 'Greek letter lambda' },
    { name: 'mu', symbol: 'μ', description: 'Greek letter mu' },
    { name: 'nu', symbol: 'ν', description: 'Greek letter nu' },
    { name: 'xi', symbol: 'ξ', description: 'Greek letter xi' },
    { name: 'pi', symbol: 'π', description: 'Greek letter pi' },
    { name: 'varpi', symbol: 'ϖ', description: 'Greek letter varpi' },
    { name: 'rho', symbol: 'ρ', description: 'Greek letter rho' },
    { name: 'varrho', symbol: 'ϱ', description: 'Greek letter varrho' },
    { name: 'sigma', symbol: 'σ', description: 'Greek letter sigma' },
    { name: 'varsigma', symbol: 'ς', description: 'Greek letter varsigma' },
    { name: 'tau', symbol: 'τ', description: 'Greek letter tau' },
    { name: 'upsilon', symbol: 'υ', description: 'Greek letter upsilon' },
    { name: 'phi', symbol: 'φ', description: 'Greek letter phi' },
    { name: 'varphi', symbol: 'ϕ', description: 'Greek letter varphi' },
    { name: 'chi', symbol: 'χ', description: 'Greek letter chi' },
    { name: 'psi', symbol: 'ψ', description: 'Greek letter psi' },
    { name: 'omega', symbol: 'ω', description: 'Greek letter omega' },
  ],

  // 希腊字母 (大写)
  greekLettersUpper: [
    { name: 'Gamma', symbol: 'Γ', description: 'Greek letter Gamma' },
    { name: 'Delta', symbol: 'Δ', description: 'Greek letter Delta' },
    { name: 'Theta', symbol: 'Θ', description: 'Greek letter Theta' },
    { name: 'Lambda', symbol: 'Λ', description: 'Greek letter Lambda' },
    { name: 'Xi', symbol: 'Ξ', description: 'Greek letter Xi' },
    { name: 'Pi', symbol: 'Π', description: 'Greek letter Pi' },
    { name: 'Sigma', symbol: 'Σ', description: 'Greek letter Sigma' },
    { name: 'Upsilon', symbol: 'Υ', description: 'Greek letter Upsilon' },
    { name: 'Phi', symbol: 'Φ', description: 'Greek letter Phi' },
    { name: 'Psi', symbol: 'Ψ', description: 'Greek letter Psi' },
    { name: 'Omega', symbol: 'Ω', description: 'Greek letter Omega' },
  ],

  // 数学运算符
  operators: [
    { name: 'sum', snippet: 'sum_{${1:i=1}}^{${2:n}} ${3}', symbol: '∑', description: 'Summation' },
    { name: 'prod', snippet: 'prod_{${1:i=1}}^{${2:n}} ${3}', symbol: '∏', description: 'Product' },
    { name: 'int', snippet: 'int_{${1:a}}^{${2:b}} ${3} \\, \\mathrm{d}${4:x}', symbol: '∫', description: 'Integral with upright d' },
    { name: 'iint', snippet: 'iint_{${1:D}} ${2} \\, \\mathrm{d}${3:x} \\, \\mathrm{d}${4:y}', symbol: '∬', description: 'Double integral with upright d' },
    { name: 'iiint', snippet: 'iiint_{${1:D}} ${2} \\, \\mathrm{d}${3:x} \\, \\mathrm{d}${4:y} \\, \\mathrm{d}${5:z}', symbol: '∭', description: 'Triple integral with upright d' },
    { name: 'oint', snippet: 'oint_{${1:C}} ${2} \\, \\mathrm{d}${3:s}', symbol: '∮', description: 'Contour integral with upright d' },
    { name: 'lim', snippet: 'lim_{${1:x \\to \\infty}} ${2}', description: 'Limit' },
    { name: 'limsup', snippet: 'limsup_{${1:n \\to \\infty}} ${2}', description: 'Superior limit' },
    { name: 'liminf', snippet: 'liminf_{${1:n \\to \\infty}} ${2}', description: 'Inferior limit' },
    { name: 'sup', description: 'Supremum' },
    { name: 'inf', description: 'Infimum' },
    { name: 'max', description: 'Maximum' },
    { name: 'min', description: 'Minimum' },
    { name: 'arg', description: 'Argument' },
    { name: 'det', description: 'Determinant' },
    { name: 'dim', description: 'Dimension' },
    { name: 'deg', description: 'Degree' },
    { name: 'ker', description: 'Kernel' },
    { name: 'hom', description: 'Homomorphism' },
    { name: 'gcd', description: 'Greatest common divisor' },
    { name: 'lcm', description: 'Least common multiple' },
    { name: 'Pr', description: 'Probability' },
    { name: 'bigcup', snippet: 'bigcup_{${1:i=1}}^{${2:n}} ${3}', symbol: '⋃', description: 'Big union' },
    { name: 'bigcap', snippet: 'bigcap_{${1:i=1}}^{${2:n}} ${3}', symbol: '⋂', description: 'Big intersection' },
    { name: 'bigoplus', snippet: 'bigoplus_{${1:i=1}}^{${2:n}} ${3}', symbol: '⨁', description: 'Big oplus' },
    { name: 'bigotimes', snippet: 'bigotimes_{${1:i=1}}^{${2:n}} ${3}', symbol: '⨂', description: 'Big otimes' },
    { name: 'bigodot', snippet: 'bigodot_{${1:i=1}}^{${2:n}} ${3}', symbol: '⨀', description: 'Big odot' },
    { name: 'bigvee', snippet: 'bigvee_{${1:i=1}}^{${2:n}} ${3}', symbol: '⋁', description: 'Big vee' },
    { name: 'bigwedge', snippet: 'bigwedge_{${1:i=1}}^{${2:n}} ${3}', symbol: '⋀', description: 'Big wedge' },
    { name: 'coprod', snippet: 'coprod_{${1:i=1}}^{${2:n}} ${3}', symbol: '∐', description: 'Coproduct' },
  ],

  // 分数、根号和数学结构
  structures: [
    { name: 'frac', snippet: 'frac{${1:numerator}}{${2:denominator}}', description: 'Fraction' },
    { name: 'dfrac', snippet: 'dfrac{${1:numerator}}{${2:denominator}}', description: 'Display fraction' },
    { name: 'tfrac', snippet: 'tfrac{${1:numerator}}{${2:denominator}}', description: 'Text fraction' },
    { name: 'cfrac', snippet: 'cfrac{${1:numerator}}{${2:denominator}}', description: 'Continued fraction' },
    { name: 'sqrt', snippet: 'sqrt{${1:expression}}', symbol: '√', description: 'Square root' },
    { name: 'sqrt[]', snippet: 'sqrt[${1:n}]{${2:expression}}', description: 'Nth root' },
    { name: 'binom', snippet: 'binom{${1:n}}{${2:k}}', description: 'Binomial coefficient' },
    { name: 'over', snippet: '{${1:numerator} \\over ${2:denominator}}', description: 'Over (TeX style)' },
    { name: 'choose', snippet: '{${1:n} \\choose ${2:k}}', description: 'Choose (TeX style)' },
    { name: 'atop', snippet: '{${1:top} \\atop ${2:bottom}}', description: 'Atop (TeX style)' },
  ],

  // 上下标和重音符号
  scripts: [
    { name: '^', snippet: '^{${1:superscript}}', description: 'Superscript' },
    { name: '_', snippet: '_{${1:subscript}}', description: 'Subscript' },
    { name: 'hat', snippet: 'hat{${1:x}}', symbol: 'x̂', description: 'Hat accent' },
    { name: 'widehat', snippet: 'widehat{${1:xyz}}', description: 'Wide hat accent' },
    { name: 'tilde', snippet: 'tilde{${1:x}}', symbol: 'x̃', description: 'Tilde accent' },
    { name: 'widetilde', snippet: 'widetilde{${1:xyz}}', description: 'Wide tilde accent' },
    { name: 'bar', snippet: 'bar{${1:x}}', symbol: 'x̄', description: 'Bar accent' },
    { name: 'overline', snippet: 'overline{${1:text}}', description: 'Overline' },
    { name: 'underline', snippet: 'underline{${1:text}}', description: 'Underline' },
    { name: 'vec', snippet: 'vec{${1:x}}', symbol: 'x⃗', description: 'Vector arrow' },
    { name: 'dot', snippet: 'dot{${1:x}}', symbol: 'ẋ', description: 'Dot accent' },
    { name: 'ddot', snippet: 'ddot{${1:x}}', symbol: 'ẍ', description: 'Double dot accent' },
    { name: 'dddot', snippet: 'dddot{${1:x}}', description: 'Triple dot accent' },
    { name: 'ddddot', snippet: 'ddddot{${1:x}}', description: 'Quadruple dot accent' },
    { name: 'acute', snippet: 'acute{${1:x}}', symbol: 'x́', description: 'Acute accent' },
    { name: 'grave', snippet: 'grave{${1:x}}', symbol: 'x̀', description: 'Grave accent' },
    { name: 'breve', snippet: 'breve{${1:x}}', symbol: 'x̆', description: 'Breve accent' },
    { name: 'check', snippet: 'check{${1:x}}', symbol: 'x̌', description: 'Check accent' },
    { name: 'mathring', snippet: 'mathring{${1:x}}', description: 'Ring accent' },
  ],

  // 括号和分隔符
  delimiters: [
    { name: 'left(', snippet: 'left(${1:expression}\\right)', description: 'Auto-sized parentheses' },
    { name: 'left[', snippet: 'left[${1:expression}\\right]', description: 'Auto-sized brackets' },
    { name: 'left\\{', snippet: 'left\\{${1:expression}\\right\\}', description: 'Auto-sized braces' },
    { name: 'left|', snippet: 'left|${1:expression}\\right|', description: 'Auto-sized vertical bars' },
    { name: 'left\\|', snippet: 'left\\|${1:expression}\\right\\|', description: 'Auto-sized double bars' },
    { name: 'langle', snippet: 'langle ${1:expression} \\rangle', symbol: '⟨⟩', description: 'Angle brackets' },
    { name: 'lceil', snippet: 'lceil ${1:expression} \\rceil', symbol: '⌈⌉', description: 'Ceiling brackets' },
    { name: 'lfloor', snippet: 'lfloor ${1:expression} \\rfloor', symbol: '⌊⌋', description: 'Floor brackets' },
    { name: 'rangle', symbol: '⟩', description: 'Right angle bracket' },
    { name: 'rceil', symbol: '⌉', description: 'Right ceiling bracket' },
    { name: 'rfloor', symbol: '⌋', description: 'Right floor bracket' },
    { name: 'big(', snippet: 'big(${1}\\big)', description: 'Big parentheses' },
    { name: 'Big(', snippet: 'Big(${1}\\Big)', description: 'Bigger parentheses' },
    { name: 'bigg(', snippet: 'bigg(${1}\\bigg)', description: 'Even bigger parentheses' },
    { name: 'Bigg(', snippet: 'Bigg(${1}\\Bigg)', description: 'Biggest parentheses' },
    { name: 'bigl(', snippet: 'bigl(${1}\\bigr)', description: 'Big left-right parentheses' },
    { name: 'Bigl(', snippet: 'Bigl(${1}\\Bigr)', description: 'Bigger left-right parentheses' },
    { name: 'biggl(', snippet: 'biggl(${1}\\biggr)', description: 'Even bigger left-right parentheses' },
    { name: 'Biggl(', snippet: 'Biggl(${1}\\Biggr)', description: 'Biggest left-right parentheses' },
  ],

  // 矩阵和数组
  matrices: [
    { name: 'matrix', snippet: 'begin{matrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{matrix}', description: 'Basic matrix' },
    { name: 'pmatrix', snippet: 'begin{pmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{pmatrix}', description: 'Matrix with parentheses' },
    { name: 'bmatrix', snippet: 'begin{bmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{bmatrix}', description: 'Matrix with brackets' },
    { name: 'Bmatrix', snippet: 'begin{Bmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{Bmatrix}', description: 'Matrix with braces' },
    { name: 'vmatrix', snippet: 'begin{vmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{vmatrix}', description: 'Matrix with vertical bars (determinant)' },
    { name: 'Vmatrix', snippet: 'begin{Vmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{Vmatrix}', description: 'Matrix with double vertical bars' },
    { name: 'smallmatrix', snippet: 'begin{smallmatrix}\n${1:a} & ${2:b} \\\\\\\n${3:c} & ${4:d}\n\\end{smallmatrix}', description: 'Small matrix' },
    { name: 'array', snippet: 'begin{array}{${1:cc}}\n${2:a} & ${3:b} \\\\\\\n${4:c} & ${5:d}\n\\end{array}', description: 'Array' },
  ],

  // 关系运算符
  relations: [
    { name: '=', symbol: '=', description: 'Equals' },
    { name: 'ne', symbol: '≠', description: 'Not equal' },
    { name: 'neq', symbol: '≠', description: 'Not equal' },
    { name: 'le', symbol: '≤', description: 'Less than or equal' },
    { name: 'leq', symbol: '≤', description: 'Less than or equal' },
    { name: 'ge', symbol: '≥', description: 'Greater than or equal' },
    { name: 'geq', symbol: '≥', description: 'Greater than or equal' },
    { name: 'll', symbol: '≪', description: 'Much less than' },
    { name: 'gg', symbol: '≫', description: 'Much greater than' },
    { name: 'equiv', symbol: '≡', description: 'Equivalent' },
    { name: 'approx', symbol: '≈', description: 'Approximately equal' },
    { name: 'sim', symbol: '∼', description: 'Similar to' },
    { name: 'simeq', symbol: '≃', description: 'Similar or equal' },
    { name: 'cong', symbol: '≅', description: 'Congruent' },
    { name: 'prec', symbol: '≺', description: 'Precedes' },
    { name: 'succ', symbol: '≻', description: 'Succeeds' },
    { name: 'preceq', symbol: '⪯', description: 'Precedes or equal' },
    { name: 'succeq', symbol: '⪰', description: 'Succeeds or equal' },
    { name: 'subset', symbol: '⊂', description: 'Subset' },
    { name: 'supset', symbol: '⊃', description: 'Superset' },
    { name: 'subseteq', symbol: '⊆', description: 'Subset or equal' },
    { name: 'supseteq', symbol: '⊇', description: 'Superset or equal' },
    { name: 'in', symbol: '∈', description: 'Element of' },
    { name: 'ni', symbol: '∋', description: 'Contains' },
    { name: 'notin', symbol: '∉', description: 'Not element of' },
    { name: 'propto', symbol: '∝', description: 'Proportional to' },
    { name: 'parallel', symbol: '∥', description: 'Parallel' },
    { name: 'perp', symbol: '⊥', description: 'Perpendicular' },
    { name: 'mid', symbol: '∣', description: 'Divides' },
    { name: 'nmid', symbol: '∤', description: 'Does not divide' },
    { name: 'models', symbol: '⊨', description: 'Models' },
    { name: 'vdash', symbol: '⊢', description: 'Proves' },
    { name: 'dashv', symbol: '⊣', description: 'Reverse proves' },
  ],

  // 二元运算符
  binops: [
    { name: 'pm', symbol: '±', description: 'Plus or minus' },
    { name: 'mp', symbol: '∓', description: 'Minus or plus' },
    { name: 'times', symbol: '×', description: 'Multiplication' },
    { name: 'div', symbol: '÷', description: 'Division' },
    { name: 'cdot', symbol: '⋅', description: 'Center dot' },
    { name: 'ast', symbol: '∗', description: 'Asterisk' },
    { name: 'star', symbol: '⋆', description: 'Star' },
    { name: 'circ', symbol: '∘', description: 'Composition' },
    { name: 'bullet', symbol: '∙', description: 'Bullet' },
    { name: 'cap', symbol: '∩', description: 'Intersection' },
    { name: 'cup', symbol: '∪', description: 'Union' },
    { name: 'sqcap', symbol: '⊓', description: 'Square intersection' },
    { name: 'sqcup', symbol: '⊔', description: 'Square union' },
    { name: 'uplus', symbol: '⊎', description: 'Multiset union' },
    { name: 'vee', symbol: '∨', description: 'Logical or' },
    { name: 'wedge', symbol: '∧', description: 'Logical and' },
    { name: 'oplus', symbol: '⊕', description: 'Direct sum' },
    { name: 'ominus', symbol: '⊖', description: 'Symmetric difference' },
    { name: 'otimes', symbol: '⊗', description: 'Tensor product' },
    { name: 'oslash', symbol: '⊘', description: 'Circled division' },
    { name: 'odot', symbol: '⊙', description: 'Circled dot' },
    { name: 'dagger', symbol: '†', description: 'Dagger' },
    { name: 'ddagger', symbol: '‡', description: 'Double dagger' },
    { name: 'amalg', symbol: '⨿', description: 'Amalgamation' },
    { name: 'wr', symbol: '≀', description: 'Wreath product' },
    { name: 'diamond', symbol: '⋄', description: 'Diamond' },
    { name: 'triangle', symbol: '△', description: 'Triangle' },
    { name: 'bigtriangleup', symbol: '△', description: 'Big triangle up' },
    { name: 'bigtriangledown', symbol: '▽', description: 'Big triangle down' },
    { name: 'triangleleft', symbol: '◁', description: 'Triangle left' },
    { name: 'triangleright', symbol: '▷', description: 'Triangle right' },
    { name: 'setminus', symbol: '∖', description: 'Set minus' },
    { name: 'ltimes', symbol: '⋉', description: 'Left semidirect product' },
    { name: 'rtimes', symbol: '⋊', description: 'Right semidirect product' },
  ],

  // 箭头
  arrows: [
    { name: 'leftarrow', symbol: '←', description: 'Left arrow' },
    { name: 'rightarrow', symbol: '→', description: 'Right arrow' },
    { name: 'leftrightarrow', symbol: '↔', description: 'Left right arrow' },
    { name: 'Leftarrow', symbol: '⇐', description: 'Left double arrow' },
    { name: 'Rightarrow', symbol: '⇒', description: 'Right double arrow' },
    { name: 'Leftrightarrow', symbol: '⇔', description: 'Left right double arrow' },
    { name: 'uparrow', symbol: '↑', description: 'Up arrow' },
    { name: 'downarrow', symbol: '↓', description: 'Down arrow' },
    { name: 'updownarrow', symbol: '↕', description: 'Up down arrow' },
    { name: 'Uparrow', symbol: '⇑', description: 'Up double arrow' },
    { name: 'Downarrow', symbol: '⇓', description: 'Down double arrow' },
    { name: 'Updownarrow', symbol: '⇕', description: 'Up down double arrow' },
    { name: 'longleftarrow', symbol: '⟵', description: 'Long left arrow' },
    { name: 'longrightarrow', symbol: '⟶', description: 'Long right arrow' },
    { name: 'longleftrightarrow', symbol: '⟷', description: 'Long left right arrow' },
    { name: 'Longleftarrow', symbol: '⟸', description: 'Long left double arrow' },
    { name: 'Longrightarrow', symbol: '⟹', description: 'Long right double arrow' },
    { name: 'Longleftrightarrow', symbol: '⟺', description: 'Long left right double arrow' },
    { name: 'mapsto', symbol: '↦', description: 'Maps to' },
    { name: 'longmapsto', symbol: '⟼', description: 'Long maps to' },
    { name: 'hookleftarrow', symbol: '↩', description: 'Hook left arrow' },
    { name: 'hookrightarrow', symbol: '↪', description: 'Hook right arrow' },
    { name: 'leftharpoonup', symbol: '↼', description: 'Left harpoon up' },
    { name: 'leftharpoondown', symbol: '↽', description: 'Left harpoon down' },
    { name: 'rightharpoonup', symbol: '⇀', description: 'Right harpoon up' },
    { name: 'rightharpoondown', symbol: '⇁', description: 'Right harpoon down' },
    { name: 'rightleftharpoons', symbol: '⇌', description: 'Right left harpoons' },
    { name: 'nearrow', symbol: '↗', description: 'Northeast arrow' },
    { name: 'searrow', symbol: '↘', description: 'Southeast arrow' },
    { name: 'swarrow', symbol: '↙', description: 'Southwest arrow' },
    { name: 'nwarrow', symbol: '↖', description: 'Northwest arrow' },
    { name: 'overleftarrow', snippet: 'overleftarrow{${1:text}}', description: 'Over left arrow' },
    { name: 'overrightarrow', snippet: 'overrightarrow{${1:text}}', description: 'Over right arrow' },
    { name: 'underleftarrow', snippet: 'underleftarrow{${1:text}}', description: 'Under left arrow' },
    { name: 'underrightarrow', snippet: 'underrightarrow{${1:text}}', description: 'Under right arrow' },
    { name: 'to', symbol: '→', description: 'To (alias for rightarrow)' },
    { name: 'gets', symbol: '←', description: 'Gets (alias for leftarrow)' },
    { name: 'iff', symbol: '⇔', description: 'If and only if' },
  ],

  // 特殊符号
  symbols: [
    { name: 'infty', symbol: '∞', description: 'Infinity' },
    { name: 'partial', symbol: '∂', description: 'Partial derivative' },
    { name: 'nabla', symbol: '∇', description: 'Nabla' },
    { name: 'forall', symbol: '∀', description: 'For all' },
    { name: 'exists', symbol: '∃', description: 'There exists' },
    { name: 'nexists', symbol: '∄', description: 'There does not exist' },
    { name: 'neg', symbol: '¬', description: 'Negation' },
    { name: 'lnot', symbol: '¬', description: 'Logical not' },
    { name: 'land', symbol: '∧', description: 'Logical and' },
    { name: 'lor', symbol: '∨', description: 'Logical or' },
    { name: 'top', symbol: '⊤', description: 'Top' },
    { name: 'bot', symbol: '⊥', description: 'Bottom' },
    { name: 'emptyset', symbol: '∅', description: 'Empty set' },
    { name: 'varnothing', symbol: '∅', description: 'Empty set (variant)' },
    { name: 'wp', symbol: '℘', description: 'Weierstrass p' },
    { name: 'ell', symbol: 'ℓ', description: 'Script l' },
    { name: 'hbar', symbol: 'ℏ', description: 'Planck constant' },
    { name: 'imath', symbol: 'ı', description: 'Dotless i' },
    { name: 'jmath', symbol: 'ȷ', description: 'Dotless j' },
    { name: 'aleph', symbol: 'ℵ', description: 'Aleph' },
    { name: 'beth', symbol: 'ℶ', description: 'Beth' },
    { name: 'gimel', symbol: 'ℷ', description: 'Gimel' },
    { name: 'daleth', symbol: 'ℸ', description: 'Daleth' },
    { name: 'Re', symbol: 'ℜ', description: 'Real part' },
    { name: 'Im', symbol: 'ℑ', description: 'Imaginary part' },
    { name: 'angle', symbol: '∠', description: 'Angle' },
    { name: 'measuredangle', symbol: '∡', description: 'Measured angle' },
    { name: 'sphericalangle', symbol: '∢', description: 'Spherical angle' },
    { name: 'backslash', symbol: '\\', description: 'Backslash' },
    { name: 'prime', symbol: '′', description: 'Prime' },
    { name: 'ldots', symbol: '…', description: 'Horizontal ellipsis' },
    { name: 'cdots', symbol: '⋯', description: 'Centered dots' },
    { name: 'vdots', symbol: '⋮', description: 'Vertical dots' },
    { name: 'ddots', symbol: '⋱', description: 'Diagonal dots' },
    { name: 'sharp', symbol: '♯', description: 'Sharp' },
    { name: 'flat', symbol: '♭', description: 'Flat' },
    { name: 'natural', symbol: '♮', description: 'Natural' },
    { name: 'clubsuit', symbol: '♣', description: 'Club suit' },
    { name: 'diamondsuit', symbol: '♢', description: 'Diamond suit' },
    { name: 'heartsuit', symbol: '♡', description: 'Heart suit' },
    { name: 'spadesuit', symbol: '♠', description: 'Spade suit' },
    { name: 'checkmark', symbol: '✓', description: 'Check mark' },
    { name: 'dag', symbol: '†', description: 'Dagger' },
    { name: 'ddag', symbol: '‡', description: 'Double dagger' },
    { name: 'S', symbol: '§', description: 'Section sign' },
    { name: 'P', symbol: '¶', description: 'Pilcrow sign' },
    { name: 'copyright', symbol: '©', description: 'Copyright sign' },
    { name: 'pounds', symbol: '£', description: 'Pound sign' },
  ],

  // 数学函数
  functions: [
    { name: 'sin', description: 'Sine function' },
    { name: 'cos', description: 'Cosine function' },
    { name: 'tan', description: 'Tangent function' },
    { name: 'cot', description: 'Cotangent function' },
    { name: 'sec', description: 'Secant function' },
    { name: 'csc', description: 'Cosecant function' },
    { name: 'arcsin', description: 'Arcsine function' },
    { name: 'arccos', description: 'Arccosine function' },
    { name: 'arctan', description: 'Arctangent function' },
    { name: 'arccot', description: 'Arccotangent function' },
    { name: 'arcsec', description: 'Arcsecant function' },
    { name: 'arccsc', description: 'Arccosecant function' },
    { name: 'sinh', description: 'Hyperbolic sine' },
    { name: 'cosh', description: 'Hyperbolic cosine' },
    { name: 'tanh', description: 'Hyperbolic tangent' },
    { name: 'coth', description: 'Hyperbolic cotangent' },
    { name: 'sech', description: 'Hyperbolic secant' },
    { name: 'csch', description: 'Hyperbolic cosecant' },
    { name: 'ln', description: 'Natural logarithm' },
    { name: 'log', description: 'Logarithm' },
    { name: 'lg', description: 'Base 2 logarithm' },
    { name: 'exp', description: 'Exponential function' },
    { name: 'operatorname', snippet: 'operatorname{${1:name}}', description: 'Operator name' },
    // 微分和积分相关的正体符号
    { name: 'mathrm', snippet: 'mathrm{${1:text}}', description: 'Roman (upright) text in math mode' },
    { name: 'd', snippet: '\\mathrm{d}', description: 'Differential d (upright)', symbol: 'd' },
    { name: 'dx', snippet: '\\mathrm{d}x', description: 'dx differential', symbol: 'dx' },
    { name: 'dy', snippet: '\\mathrm{d}y', description: 'dy differential', symbol: 'dy' },
    { name: 'dz', snippet: '\\mathrm{d}z', description: 'dz differential', symbol: 'dz' },
    { name: 'dt', snippet: '\\mathrm{d}t', description: 'dt differential', symbol: 'dt' },
    { name: 'dr', snippet: '\\mathrm{d}r', description: 'dr differential', symbol: 'dr' },
    { name: 'dtheta', snippet: '\\mathrm{d}\\theta', description: 'dθ differential', symbol: 'dθ' },
    { name: 'dphi', snippet: '\\mathrm{d}\\phi', description: 'dφ differential', symbol: 'dφ' },
    // 常用的正体常数和函数
    { name: 'e', snippet: '\\mathrm{e}', description: 'Euler\'s number (upright)', symbol: 'e' },
    { name: 'i', snippet: '\\mathrm{i}', description: 'Imaginary unit (upright)', symbol: 'i' },
    { name: 'j', snippet: '\\mathrm{j}', description: 'Imaginary unit j (upright)', symbol: 'j' },
  ],

  // 数学常数和单位（正体）
  constants: [
    { name: 'pi', symbol: 'π', description: 'Pi (use \\mathrm for upright)' },
    { name: 'uppi', snippet: '{\\mathrm{\\pi}}', symbol: 'π', description: 'Upright pi' },
    { name: 'upe', snippet: '{\\mathrm{e}}', symbol: 'e', description: 'Upright Euler number' },
    { name: 'upi', snippet: '{\\mathrm{i}}', symbol: 'i', description: 'Upright imaginary unit' },
    { name: 'upj', snippet: '{\\mathrm{j}}', symbol: 'j', description: 'Upright imaginary unit j' },
    { name: 'kg', snippet: '\\,\\mathrm{kg}', description: 'Kilogram unit (upright)' },
    { name: 'm', snippet: '\\,\\mathrm{m}', description: 'Meter unit (upright)' },
    { name: 's', snippet: '\\,\\mathrm{s}', description: 'Second unit (upright)' },
    { name: 'mol', snippet: '\\,\\mathrm{mol}', description: 'Mole unit (upright)' },
    { name: 'rad', snippet: '\\,\\mathrm{rad}', description: 'Radian unit (upright)' },
    { name: 'deg', snippet: '^\\circ', description: 'Degree symbol' },
  ],

  // 数学字体
  fonts: [
    { name: 'mathbb', snippet: 'mathbb{${1:text}}', description: 'Blackboard bold' },
    { name: 'mathbf', snippet: 'mathbf{${1:text}}', description: 'Bold face' },
    { name: 'mathcal', snippet: 'mathcal{${1:text}}', description: 'Calligraphic' },
    { name: 'mathfrak', snippet: 'mathfrak{${1:text}}', description: 'Fraktur' },
    { name: 'mathit', snippet: 'mathit{${1:text}}', description: 'Italic' },
    { name: 'mathrm', snippet: 'mathrm{${1:text}}', description: 'Roman' },
    { name: 'mathsf', snippet: 'mathsf{${1:text}}', description: 'Sans serif' },
    { name: 'mathtt', snippet: 'mathtt{${1:text}}', description: 'Typewriter' },
    { name: 'boldsymbol', snippet: 'boldsymbol{${1:text}}', description: 'Bold symbol' },
    { name: 'text', snippet: 'text{${1:text}}', description: 'Text in math mode' },
    { name: 'textrm', snippet: 'textrm{${1:text}}', description: 'Roman text in math' },
    { name: 'textit', snippet: 'textit{${1:text}}', description: 'Italic text in math' },
    { name: 'textbf', snippet: 'textbf{${1:text}}', description: 'Bold text in math' },
    { name: 'texttt', snippet: 'texttt{${1:text}}', description: 'Typewriter text in math' },
  ],

  // 数学样式
  styles: [
    { name: 'displaystyle', description: 'Display style' },
    { name: 'textstyle', description: 'Text style' },
    { name: 'scriptstyle', description: 'Script style' },
    { name: 'scriptscriptstyle', description: 'Script script style' },
  ],

  // 环境
  environments: [
    { name: 'document', snippet: 'begin{document}\n${1}\n\\end{document}', description: 'Document environment' },
    { name: 'equation', snippet: 'begin{equation}\n${1}\n\\end{equation}', description: 'Numbered equation' },
    { name: 'equation*', snippet: 'begin{equation*}\n${1}\n\\end{equation*}', description: 'Unnumbered equation' },
    { name: 'align', snippet: 'begin{align}\n${1}\n\\end{align}', description: 'Aligned equations' },
    { name: 'align*', snippet: 'begin{align*}\n${1}\n\\end{align*}', description: 'Unnumbered aligned equations' },
    { name: 'gather', snippet: 'begin{gather}\n${1}\n\\end{gather}', description: 'Gathered equations' },
    { name: 'gather*', snippet: 'begin{gather*}\n${1}\n\\end{gather*}', description: 'Unnumbered gathered equations' },
    { name: 'split', snippet: 'begin{split}\n${1}\n\\end{split}', description: 'Split equation' },
    { name: 'multline', snippet: 'begin{multline}\n${1}\n\\end{multline}', description: 'Multi-line equation' },
    { name: 'multline*', snippet: 'begin{multline*}\n${1}\n\\end{multline*}', description: 'Unnumbered multi-line equation' },
    { name: 'eqnarray', snippet: 'begin{eqnarray}\n${1}\n\\end{eqnarray}', description: 'Equation array (deprecated)' },
    { name: 'eqnarray*', snippet: 'begin{eqnarray*}\n${1}\n\\end{eqnarray*}', description: 'Unnumbered equation array (deprecated)' },
    { name: 'cases', snippet: 'begin{cases}\n${1:case1} & \\text{if } ${2:condition1} \\\\\\\n${3:case2} & \\text{if } ${4:condition2}\n\\end{cases}', description: 'Cases' },
    { name: 'itemize', snippet: 'begin{itemize}\n\\item ${1}\n\\end{itemize}', description: 'Bullet list' },
    { name: 'enumerate', snippet: 'begin{enumerate}\n\\item ${1}\n\\end{enumerate}', description: 'Numbered list' },
    { name: 'description', snippet: 'begin{description}\n\\item[${1:term}] ${2:description}\n\\end{description}', description: 'Description list' },
    { name: 'center', snippet: 'begin{center}\n${1}\n\\end{center}', description: 'Centered text' },
    { name: 'quote', snippet: 'begin{quote}\n${1}\n\\end{quote}', description: 'Quote environment' },
    { name: 'quotation', snippet: 'begin{quotation}\n${1}\n\\end{quotation}', description: 'Quotation environment' },
    { name: 'verse', snippet: 'begin{verse}\n${1}\n\\end{verse}', description: 'Verse environment' },
    { name: 'verbatim', snippet: 'begin{verbatim}\n${1}\n\\end{verbatim}', description: 'Verbatim text' },
    { name: 'flushleft', snippet: 'begin{flushleft}\n${1}\n\\end{flushleft}', description: 'Left-aligned text' },
    { name: 'flushright', snippet: 'begin{flushright}\n${1}\n\\end{flushright}', description: 'Right-aligned text' },
    { name: 'table', snippet: 'begin{table}[${1:htbp}]\n\\centering\n\\caption{${2:caption}}\n\\label{${3:label}}\n\\begin{tabular}{${4:cc}}\n${5}\n\\end{tabular}\n\\end{table}', description: 'Table environment' },
    { name: 'figure', snippet: 'begin{figure}[${1:htbp}]\n\\centering\n\\includegraphics[${2:options}]{${3:filename}}\n\\caption{${4:caption}}\n\\label{${5:label}}\n\\end{figure}', description: 'Figure environment' },
    { name: 'tabular', snippet: 'begin{tabular}{${1:cc}}\n${2}\n\\end{tabular}', description: 'Tabular environment' },
    { name: 'array', snippet: 'begin{array}{${1:cc}}\n${2:a} & ${3:b} \\\\\\\n${4:c} & ${5:d}\n\\end{array}', description: 'Array environment' },
    { name: 'minipage', snippet: 'begin{minipage}{${1:width}}\n${2}\n\\end{minipage}', description: 'Minipage environment' },
    { name: 'proof', snippet: 'begin{proof}\n${1}\n\\end{proof}', description: 'Proof environment' },
    { name: 'theorem', snippet: 'begin{theorem}\n${1}\n\\end{theorem}', description: 'Theorem environment' },
    { name: 'lemma', snippet: 'begin{lemma}\n${1}\n\\end{lemma}', description: 'Lemma environment' },
    { name: 'definition', snippet: 'begin{definition}\n${1}\n\\end{definition}', description: 'Definition environment' },
    { name: 'example', snippet: 'begin{example}\n${1}\n\\end{example}', description: 'Example environment' },
    { name: 'remark', snippet: 'begin{remark}\n${1}\n\\end{remark}', description: 'Remark environment' },
  ]
};

// 将所有数据合并为一个扁平的数组，用于Monaco补全
export function getLatexCompletionItems() {
  const items = [];
  
  // 处理各个分类的数据
  Object.values(latexCompletionData).forEach(category => {
    if (Array.isArray(category)) {
      category.forEach(item => {
        const insertText = item.snippet || item.name;
        const detail = item.symbol || item.detail || item.name;
        
        const completionItem = {
          label: `\\${item.name}`,
          insertText: insertText.startsWith('\\') ? insertText : `\\${insertText}`,
          detail: detail,
          documentation: item.description,
          kind: 'Function', // Monaco会转换为相应的CompletionItemKind
          insertTextRules: item.snippet ? 'InsertAsSnippet' : 'None'
        };
        items.push(completionItem);
      });
    }
  });
  
  return items;
}

export default latexCompletionData;
